networks:
  app:
    name: botool_app

volumes:
  db_data:

services:
  php:
    build: .docker/php
    container_name: php
    volumes:
      - ./:/var/www/html
    networks:
      - app
  caddy:
    image: caddy:latest
    container_name: caddy
    depends_on:
      - php
    volumes:
      - .docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www/html
    ports:
      - "80:80"
    networks:
      - app
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql
